language: generic
sudo: false
dist: trusty
os: linux

branches:
  only:
    - master

env:
  global:
    - secure: "hZ2ZQ1Ae+kWxqmquLRVfuksyUaySPlOknxzB3ud/lFmSRcVRyOa+K4+F5+8B+Tb2HQ3mihXAqlsV6KlCw8yuMr4b1Kf3dBHCGmr0xMYSueCs4hHqfDb4mesdlWlJGW8lHhPXG2CTyrooZOC+Q5qXjgSxyRi3EZiBL/rCLUVT+yPNNpno1+VvT+DyLvNi9JgCtG/eFvX3LbndBEh514kIXfZNWtxLAe1kLsjV3SZXvIgPoFpYLtxqAVy0EsLnKszfvogev+5lbLdHI72R9GkbUz9WT4Q4UQ6iKJ6EC2CvvSB/aCvHYvsoqQQw6O8ildXDCsRn7yQomBbs0QNtQDt8ZGke+IwBYCe2WwLto178Tdunsq5/tJ5hRaZXqFg5UvNlr8U+Fi2oUA7MWVfNfF2GW02g7hR4HSWJTut7UNRulGOTEgwbqX1h+pcdrhj4iZWquy0Ip9I7trGuMON9ZxSa88L8BMsjwnqxjMbkrSpV8Aqgz88HuiM9wtADLBkNa9CL0ZleSZRcsBVN59s/gfR4EaM1Ej5BU9qP+bXKmh+DNWRy04keh75KwnabakYBArtJ0PM8mbshDFzBm8P+X4O3IbD7FZ5+7GB8sDyr+216McednspFWUkT1RJ0rmsK/6B4suwuAwecXqeFjVT9bBxG2vjrPwo22Kk1lfG+V1y1s4g="

jobs:
  fast_finish: true
  include:
    - env:
      - PYTHON=2.7

    - env:
      - PYTHON=3.6
      - DOCS=true

install:
  - source testing/ci/install_conda.sh
  - ./testing/setup_envs.sh
  - conda install -y flake8 pytest
  - |
    if [[ "$DOCS" == "true" ]]; then
        conda install -y sphinx numpydoc
        pip install sphinxcontrib.autoprogram
    fi
  - pip install .

script:
  - py.test conda_pack
  - flake8 conda_pack
  - |
    if [[ "$DOCS" == "true" ]]; then
        pushd docs && make html && popd
    fi

after_success:
  - |
    if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_EVENT_TYPE" == "push" ]]; then
      pip install doctr
      doctr deploy . --built-docs docs/build/html/
    fi

notifications:
  email: false
