language: generic
sudo: false
dist: trusty
os: linux

branches:
  only:
    - master

env:
  global:
    - secure: "hZ2ZQ1Ae+kWxqmquLRVfuksyUaySPlOknxzB3ud/lFmSRcVRyOa+K4+F5+8B+Tb2HQ3mihXAqlsV6KlCw8yuMr4b1Kf3dBHCGmr0xMYSueCs4hHqfDb4mesdlWlJGW8lHhPXG2CTyrooZOC+Q5qXjgSxyRi3EZiBL/rCLUVT+yPNNpno1+VvT+DyLvNi9JgCtG/eFvX3LbndBEh514kIXfZNWtxLAe1kLsjV3SZXvIgPoFpYLtxqAVy0EsLnKszfvogev+5lbLdHI72R9GkbUz9WT4Q4UQ6iKJ6EC2CvvSB/aCvHYvsoqQQw6O8ildXDCsRn7yQomBbs0QNtQDt8ZGke+IwBYCe2WwLto178Tdunsq5/tJ5hRaZXqFg5UvNlr8U+Fi2oUA7MWVfNfF2GW02g7hR4HSWJTut7UNRulGOTEgwbqX1h+pcdrhj4iZWquy0Ip9I7trGuMON9ZxSa88L8BMsjwnqxjMbkrSpV8Aqgz88HuiM9wtADLBkNa9CL0ZleSZRcsBVN59s/gfR4EaM1Ej5BU9qP+bXKmh+DNWRy04keh75KwnabakYBArtJ0PM8mbshDFzBm8P+X4O3IbD7FZ5+7GB8sDyr+216McednspFWUkT1RJ0rmsK/6B4suwuAwecXqeFjVT9bBxG2vjrPwo22Kk1lfG+V1y1s4g="

jobs:
  fast_finish: true
  include:
    - env:
      - PYTHON=2.7
    - env:
      - PYTHON=3.6
    - env:
      - PYTHON=3.7
    - env:
      - PYTHON=3.8
      - DOCS=true
  allow_failures:
    - env: PYTHON=2.7

install:
  - wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-linux-64.exe -O conda.exe
  - chmod +x conda.exe
  - ./conda.exe config --add channels conda-forge
  - ./conda.exe create -y -p $HOME/conda conda-build conda-verify flake8
  - source $HOME/conda/bin/activate
  
script:
  - conda build conda-recipe
  - |
    if [[ "$DOCS" = "true" ]]; then
        cd docs
        conda install -y --use-local sphinx numpydoc doctr sphinxcontrib-autoprogram make conda-pack
        make html || exit -1
    fi

after_success:
  - |
    if [[ "$DOCS" = "true" && $TRAVIS_BRANCH" == "master" && "$TRAVIS_EVENT_TYPE" == "push" ]]; then
        doctr deploy . --built-docs build/html/
    fi

notifications:
  email: false
