package:
  name: conda_pack_test_lib1
  version: 0.0.1

source:
  path: ../

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - setuptools
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - conda_pack_test_lib1

about:
  home: https://github.com/conda/conda-pack
  summary: Dummy package for testing conda-pack
