{% set data = load_setup_py_data() %}

package:
  name: conda-pack
  version: {{ data.get('version').lstrip('v') }}

source:
  path: ../

build:
  number: 0
  noarch: python
  script:
      - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  entry_points:
    - conda-pack = conda_pack.cli:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - setuptools

test:
  source_files:
    - testing
    - conda_pack/tests
  requires:
    - python
    - pytest
    - squashfs-tools
    - squashfuse
  commands:
    - bash testing/setup_envs.sh
    - pytest -s -vv conda_pack/tests

about:
  home: https://conda.github.io/conda-pack/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Package conda environments for redistribution'
  description: |
    ``conda-pack`` is a command line tool for creating relocatable conda
    environments. This is useful for deploying code in a consistent environment,
    potentially in a location where python/conda isn't already installed.
  doc_url: https://conda.github.io/conda-pack/
  dev_url: https://github.com/conda/conda-pack
